[package]
name = "ingles"
version = "0.1.1"
authors = ["lim <liam@liamiam.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
log = "0.4.11"
simple_logger = "1.6.0"
